# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    binary: mgr
    main: ./cmd/main.go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
ignore:
  - goos: windows
    goarch: arm64
# release:
#   prerelease: auto
# brews:
#   - name: ploy
#     tap:
#       owner: jaxxstorm
#       name: homebrew-tap
#     commit_author:
#       name: GitHub Actions
#       email: bot@leebriggs.co.uk
#     folder: Formula
#     homepage: "https://leebriggs.co.uk"
#     description: "Quickly install applications to Kubernetes with Pulumi"
